#!/usr/bin/env python
# -*- coding: utf-8 -*-

APP_NAME = ''
APP_DOMAIN = ''
APP_DEBUG = True
APP_ADMINS = ['your_nick']
APP_DEFAULT_COOKIE_EXPIRATION = 1209600
APP_PORT = 8080

MYSQL_HOST = 'localhost'
MYSQL_PORT = '3306'
MYSQL_USER = 'root'
MYSQL_PASS = ''
MYSQL_DBNAME = ''

APP_ADMIN_EMAIL = ''
SMTP_SERVER = ''
SMTP_PORT = 587
SMTP_USER = ''
SMTP_PASS = ''
SMTP_TTLS = True

UBUNTUFAQ_USER_NICK = ''
UBUNTUFAQ_USER_EMAIL = ''
